### ISSUE TITLE
TypeError: timeString.toLowerCase is not a function

### ISSUE THREAD

**Issue by brandonkelly** [jonthornton/jquery-timepicker#722]
The following code worked in 1.13.0 - 1.13.4:

```js
// set time to 12:00
$('#my-timepicker').timepicker('setTime', 43200);
```

But as of 1.13.5, it now causes a JS error:

```
TypeError: timeString.toLowerCase is not a function
```

it’s coming from this line:

https://github.com/jonthornton/jquery-timepicker/blob/f78442fa66d45b6c1b344144743d60dcae0c4753/src/timepicker/index.js#L43

Appears that the bug was introduced by 910bcfaabfa29eb71a9edc1803a3029ae1e085ca.

It continues to exist on the latest release, 1.13.9.

**Comment by jonthornton** [comment]
Sorry about that! Thanks for the heads up.

**Comment by brandonkelly** [comment]
Works great now. Thanks for the quick fix!
